Month 9/step 2
Zdthns/burger pull request #2
Opened 2023-01-08 09:07 UTC by Zdthns

2023-01-08 09:59 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)


К сожалению, работу придется отклонить без потери итерации


* не могу установить пакеты. Скрин ошибок https://disk.yandex.ru/i/qG9SBddEeoyjUQ 

Еще заметил ошибки:

* Файл `App.test.js` нужно удалить, так как он не относится к проекту
* базовый урл должен быть один в проекте. Не нужно его объявлять в разных файлах
* `const checkResponse ` тоже нужно 1 раз создать. Не нужно дублировать код
*

2023-01-08 09:59 UTC, gennady-bars commented on src/utils/userApi.js
> +  }).then(checkResponse);
**Можно лучше**

Можно сделать **универсальную функцию запроса с проверкой ответа**, чтобы не дублировать эту проверку в каждом запросе:

```js

  function request(url, options) {
    // принимает два аргумента: урл и объект опций, как и `fetch`
    return fetch(url, options).then(checkResponse)
  }

```

И теперь просто нужно заменить все `fetch` на `request` и убрать дублирование проверки на `ok`. Все остальное будет без изменений. Код станет чище

2023-01-08 09:59 UTC, gennady-bars commented on src/utils/burger.js
> +const api = "https://norma.nomoreparties.space/api";
базовый урл должен быть один в проекте. Не нужно его объявлять в разных файлах

2023-01-08 09:59 UTC, gennady-bars commented on src/utils/userApi.js
> +const api = "https://norma.nomoreparties.space/api";
базовый урл должен быть один в проекте. Не нужно его объявлять в разных файлах

2023-01-08 09:59 UTC, gennady-bars commented on src/utils/userApi.js
> +const api = "https://norma.nomoreparties.space/api";
`'https://norma.nomoreparties.space/api` везде повторяется в запросах. Нужно вынести в константу `BASE_URL` и импортировать везде в коде проекта, добавляя в конце изменяющуюся часть (эндпоит). Это обычная практика, чтобы одним движением можно было **сменить адрес**, но не менять эндпоинты.

2023-01-08 09:59 UTC, gennady-bars commented on src/utils/userApi.js
> +const checkResponse = (res) => {
`const checkResponse ` тоже нужно 1 раз создать. Не нужно дублировать код

2023-01-08 09:59 UTC, gennady-bars commented on src/utils/burger.js
> +const checkResponse = (res) => {
`const checkResponse ` тоже нужно 1 раз создать. Не нужно дублировать код

2023-01-08 10:00 UTC, gennady-bars commented on src/pages/LoginPage/LoginPage.jsx
> +  const [form, setForm] = React.useState({ email: "", password: "" });
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = (event) => {
    const {value, name} = event.target;
    setValues({...values, [name]: value});
  };
  return {values, handleChange, setValues};
}

```

Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```jsx
  const {values, handleChange, setValues} = useForm({});

```

2023-01-08 10:01 UTC, gennady-bars reviewed
*

2023-01-08 10:01 UTC, gennady-bars commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +function RouterProvider({ children, isAuth, ...props }) {
` ProtectedRoute` должен использовать ` Redirect`  с параметрами для универсального **возращения** пользователя обратно туда, куда он хотел попасть.
```js

 <Redirect to={{ pathname: "/login", state: { from: location } }} />

```

2023-01-08 10:01 UTC, gennady-bars commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +function RouterProvider({ children, isAuth, ...props }) {
**Можно лучше**

Если интересно, то можно сделать вот так универсальный компонент `ProtectedRoute` с переадресацией

```jsx


export default function ProtectedRoute({ children, anonymous = false }) {
  const isLoggedIn = useSelector((store) => store.user.isLoggedIn);

  const location = useLocation();
  const from = location.state?.from || '/';
  // Если разрешен неавторизованный доступ, а пользователь авторизован...
  if (anonymous && isLoggedIn) {
    // ...то отправляем его на предыдущую страницу
    return <Navigate to={ from } />;
  }

  // Если требуется авторизация, а пользователь не авторизован...
  if (!anonymous && !isLoggedIn) {
    // ...то отправляем его на страницу логин
    return <Navigate to="/login" state={{ from: location}}/>;
  }

  // Если все ок, то рендерим внутреннее содержимое
  return children;
}

```

2023-01-08 12:20 UTC, Zdthns commented on src/pages/LoginPage/LoginPage.jsx
> +  const [form, setForm] = React.useState({ email: "", password: "" });
супер! спасибо)

2023-01-08 12:21 UTC, Zdthns commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +function RouterProvider({ children, isAuth, ...props }) {
Классно! Спасибо)

2023-01-08 19:14 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Работа проделана огромная


* Отлично, что обработчик сабмита вешаете на форму, а не клик на кнопку.

но есть некоторые недочеты: 

* в консоли ошибки https://disk.yandex.ru/i/c-W1Y9rEtcZrNw 
* сквозь оверлей должна быть видна главная страница. Скрин https://disk.yandex.ru/i/0C14_taDolfWcA . Попап открывается над ней. Она не должна пропадать, иначе это приводит к постоянной перерисовке всего контента
* по заданию нужно сделать логику, при которой бы показывался попап с деталями ингредиента, если кликнуть по ингредиенту, но если скопировать ссылку на ингредиент при открытом попапе и **вставить в окно браузера**, то должна уже показываться **страница** с этими деталями. 
* если **перезагрузить** страницу с открытым попапом ингредиента, то этот открытый попап опять должен появляться (или страница с деталями). А сейчас ничего не отображается после перезагрузки
* А сейчас при вышеуказанных действиях пустой попап https://disk.yandex.ru/i/KBZJmGvTZw7P-g 
* не могу восстановить пароль. Скрин, что показывает после отправки кода на мэйл https://disk.yandex.ru/i/k8QzlXzZV-037w 
* пользователь не должен **напрямую** попасть на маршрут `/reset-password`. На эту страницу **никакой** пользователь не должен попадать напрямую. Только после нажатия на `восстановить пароль` нужно делать переход на эту страницу. Для этого нужно сделать проверку, был ли пользователь на странице `forgot-password` перед тем, как попасть на `reset-password`
* В верхней булке нужно добавлять текст `верх`, а в нижней - `низ`. Посмотрите в фигме, пожалуйста
* `dispatch(getIngredients())` достаточно 1 раз сделать в `App`, чтобы все страницы получили ингредиенты при загрузке сайта. Не нужно дублировать запрос в других компонентах.
* 


**Можно лучше**

*  желательно **очищать конструктор** после успешного получения номера заказа с сервера в блоке `then`, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты
*  при клике на **логотип** обычно идет переход на главную страницу
* лучше отображать **лоадер** (загрузку) при ожидании ответа от сервера с номером заказа.


Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте **работоспособность проекта** и наличие возможных ошибок в консоли браузера (кнопка `F12`) перед отправкой на ревью. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний `Нужно исправить`.

Удачного рефакторинга кода.

2023-01-08 19:14 UTC, gennady-bars commented on src/components/Form/Form.jsx
> +    <form className={style.form} onSubmit={onSubmit}>
Отлично, что обработчик сабмита вешаете на форму, а не клик на кнопку. Обработка события `submit` еще срабатывает при нажатии на `Enter`, так как это встроенная логика сабмитов в браузере.

2023-01-08 19:14 UTC, gennady-bars commented on src/pages/HomePage/HomePage copy.jsx
> +    dispatch(getIngredients());
`dispatch(getIngredients())` достаточно 1 раз сделать в `App`, чтобы все страницы получили ингредиенты при загрузке сайта. Не нужно дублировать запрос в других компонентах.

2023-01-10 10:38 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

К сожалению, работу придется отклонить без потери итерации

* не могу залогиниться. Ничего не происходит при клике или сабмите формы логина
* в консоли ошибки при входе в логин или восстановление пароля https://disk.yandex.ru/i/iMdP2F9Czh6HMA

2023-01-10 10:38 UTC, gennady-bars commented on src/components/App/App.jsx
> +    dispatch(wsConnectionStart());
Нельзя открывать соединения сокетов в `App` сразу при загрузке сайта. Пользователь даже может не зайти на страницы ленты или истории, а соединения будут открыты. Это лишняя нагрузка на сервер и приложение


но это задание следующего спринта, поэтому я пока просто тут пишу. Не буду проверять эту логику сокетов

2023-01-10 12:20 UTC, gennady-bars approved these changes
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2023-01-10 17:29 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали неплохую работу по добавлению ленты заказов в ваш проект, правильно подключили мидлвари отдельно для каждого экрана, хорошо сверстали новые страницы.
Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует центрировать текст в ссылках в хедере относительно иконок (см. https://disk.yandex.ru/i/5daYN1C9T7cWqg);
- В рамках сокета вам приходит большее кол-во номеров заказов, чем 10, следует отобразить их все, с учетом, что в каждой колонке может быть не более 10 элементов (см. https://disk.yandex.ru/i/5fBGjr0XVo1SGg);
- Некорректно отображается элемент, в котором указывается сколько еще "+" элементов внутри заказа (см. https://disk.yandex.ru/i/uStP583SwhXAWw);
- При прямом переходе по ссылке на экран не подсвечивается белым цветом иконка активной ссылки в хедере (см. https://disk.yandex.ru/i/MoPteSS9xSwo-g);
- Следует центрировать форму на экране логина, согласно дизайну (см. https://disk.yandex.ru/i/skd9vQ6eiE6TYw);
- Следует скорректировать отступы и шрифты бокового меню, согласно дизайну и добавить подсказки для полей формы редактирования профиля (см. https://disk.yandex.ru/i/-vvA4Cc53c9cSg);
- Следует расширить карточку булки в конструкторе относительно ингредиентов, согласно дизайну (см. https://disk.yandex.ru/i/U6ywumB6z0MjPw);
- На экране истории заказов:
  - Текст под боковым меню не соответствует дизайну, следует заменить на "" (https://disk.yandex.ru/i/7TF3CaK2aw-aPQ);
  - Список заказов занимает очень малое пространство на экране, следует увеличить его площадь, в идеале до полной высоты, с учетом отступов сверху и снизу, как в дизайне (см. дизайн https://disk.yandex.ru/i/3BVlX0BHQeGRtg);
- При переходе по прямой ссылке на экран "История заказов" приложение падает с ошибкой вечного цикла (см. https://disk.yandex.ru/i/qVKcyCcFXh2Xug);
- В модальном окне указывается неверный номер заказа (см. https://disk.yandex.ru/i/3YNOSwoVIV5ZTg);
- При уходе с экранов "Лента заказов" и "История заказов" следует закрывать сокет-соединение (см. https://disk.yandex.ru/i/9ixmAWqt83Kq3g);
- На форме восстановления пароля по роуту `/reset-password`:
  - Инпуты синхронизированы между собой;
  - У инпутов присутствует начальное значение = `password` - следует его убрать (см. https://disk.yandex.ru/i/BxhpnN7dgE1WCg);
  - Не происходит вызов API при попытке отправки;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-01-11 14:56 UTC, Zdthns commented
Не могу воспроизвести данную ситуацию: При переходе по прямой ссылке на экран "История заказов" приложение падает с ошибкой вечного цикла (см. https://disk.yandex.ru/i/qVKcyCcFXh2Xug); - У меня ошибок нет. Вот видео попытки воспроизведения https://disk.yandex.ru/i/ZJDBqVKvQguX3g

2023-01-12 13:52 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остались несколько моментов, которые следует также исправить для сдачи проекта на данном этапе:

- На форме восстановления пароля по роуту `/reset-password` не происходит вызов API при попытке отправки (например по нажатию кнопки "Сохранить") из-за совпадений имен функций в компоненте (https://disk.yandex.ru/i/YAUYZWZDyxdRFA, https://disk.yandex.ru/i/BGSQchYLiwQn3w)
- При прямом переходе на маршрут `/profile/orders/:id` следует открывать страницу заказа или соответствующее модальное окно, как при нажатии;
- При уходе с экранов "Лента заказов" и "История заказов" следует закрывать сокет-соединение (см. https://disk.yandex.ru/i/9ixmAWqt83Kq3g). В текущей реализации у вас возникает конфликт из-за наличия `_CLOSE` и `_CLOSED` (https://disk.yandex.ru/i/boD4YQmgrLJT6A), поэтому ожидаемый вызов не происходит.

**Хорошего вам дня и настроения!** 🐈

2023-01-12 13:52 UTC, randomroot commented on src/components/Navigation/Navigation.jsx
> +  const isProfile = location.pathname.includes("/profile");
🟡 **Можно улучшить:**

Для определения текущего урла можно использовать хук `useRouteMatch` (см. https://v5.reactrouter.com/web/api/Hooks/useroutematch)

2023-01-12 13:52 UTC, randomroot commented on src/pages/ResetPassword/ResetPassword.jsx
> +      <div style={{ display: "flex", flexDirection: "column" }}>
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2023-01-12 13:52 UTC, randomroot commented on src/pages/ResetPassword/ResetPassword.jsx
>    function resetPassword() {
🔴 **Нужно исправить:**

Т.к. совпадают имени функции внутри компонента и импортируемой из Redux-a, то при сабмите формы будет вызвана именно эта функция и, соответственно, вызова API не произойдет.

2023-01-13 16:56 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Перед тем как слить ветку в `main` следует исправить в API запросе на форме `reset-password` в теле запроса следует отправлять `token` (вместо `cod`) и `password`.

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-01-22 19:10 UTC, merged